services:
  - type: web
    name: devpulse-blog-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py seed_data"
    startCommand: "gunicorn blog_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
